// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string firstName = 2;</code>
     */
    boolean hasFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>required string lastName = 3;</code>
     */
    boolean hasLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    java.util.List<CustomerProtos.Customer.EmailAddress>
        getEmailList();
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    CustomerProtos.Customer.EmailAddress getEmail(int index);
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    int getEmailCount();
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    java.util.List<? extends CustomerProtos.Customer.EmailAddressOrBuilder>
        getEmailOrBuilderList();
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.test.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.test.Customer)
      CustomerOrBuilder {
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Customer() {
      id_ = 0;
      firstName_ = "";
      lastName_ = "";
      email_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              firstName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              lastName_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                email_ = new java.util.ArrayList<CustomerProtos.Customer.EmailAddress>();
                mutable_bitField0_ |= 0x00000008;
              }
              email_.add(input.readMessage(CustomerProtos.Customer.EmailAddress.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = java.util.Collections.unmodifiableList(email_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProtos.internal_static_com_test_Customer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProtos.internal_static_com_test_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerProtos.Customer.class, CustomerProtos.Customer.Builder.class);
    }

    /**
     * Protobuf enum {@code com.test.Customer.EmailType}
     */
    public enum EmailType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PRIVATE = 1;</code>
       */
      PRIVATE(0, 1),
      /**
       * <code>PROFESSIONAL = 2;</code>
       */
      PROFESSIONAL(1, 2),
      ;

      /**
       * <code>PRIVATE = 1;</code>
       */
      public static final int PRIVATE_VALUE = 1;
      /**
       * <code>PROFESSIONAL = 2;</code>
       */
      public static final int PROFESSIONAL_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static EmailType valueOf(int value) {
        switch (value) {
          case 1: return PRIVATE;
          case 2: return PROFESSIONAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EmailType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EmailType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EmailType>() {
              public EmailType findValueByNumber(int number) {
                return EmailType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CustomerProtos.Customer.getDescriptor().getEnumTypes().get(0);
      }

      private static final EmailType[] VALUES = values();

      public static EmailType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EmailType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.test.Customer.EmailType)
    }

    public interface EmailAddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.test.Customer.EmailAddress)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string email = 1;</code>
       */
      boolean hasEmail();
      /**
       * <code>required string email = 1;</code>
       */
      java.lang.String getEmail();
      /**
       * <code>required string email = 1;</code>
       */
      com.google.protobuf.ByteString
          getEmailBytes();

      /**
       * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
       */
      boolean hasType();
      /**
       * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
       */
      CustomerProtos.Customer.EmailType getType();
    }
    /**
     * Protobuf type {@code com.test.Customer.EmailAddress}
     */
    public  static final class EmailAddress extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.test.Customer.EmailAddress)
        EmailAddressOrBuilder {
      // Use EmailAddress.newBuilder() to construct.
      private EmailAddress(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private EmailAddress() {
        email_ = "";
        type_ = 2;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private EmailAddress(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                email_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                CustomerProtos.Customer.EmailType value = CustomerProtos.Customer.EmailType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = rawValue;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProtos.internal_static_com_test_Customer_EmailAddress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProtos.internal_static_com_test_Customer_EmailAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerProtos.Customer.EmailAddress.class, CustomerProtos.Customer.EmailAddress.Builder.class);
      }

      private int bitField0_;
      public static final int EMAIL_FIELD_NUMBER = 1;
      private volatile java.lang.Object email_;
      /**
       * <code>required string email = 1;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
       */
      public CustomerProtos.Customer.EmailType getType() {
        CustomerProtos.Customer.EmailType result = CustomerProtos.Customer.EmailType.valueOf(type_);
        return result == null ? CustomerProtos.Customer.EmailType.PROFESSIONAL : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasEmail()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getEmailBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getEmailBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static CustomerProtos.Customer.EmailAddress parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static CustomerProtos.Customer.EmailAddress parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CustomerProtos.Customer.EmailAddress prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.test.Customer.EmailAddress}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.test.Customer.EmailAddress)
          CustomerProtos.Customer.EmailAddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CustomerProtos.internal_static_com_test_Customer_EmailAddress_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CustomerProtos.internal_static_com_test_Customer_EmailAddress_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CustomerProtos.Customer.EmailAddress.class, CustomerProtos.Customer.EmailAddress.Builder.class);
        }

        // Construct using com.example.CustomerProtos.Customer.EmailAddress.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          email_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 2;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CustomerProtos.internal_static_com_test_Customer_EmailAddress_descriptor;
        }

        public CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
          return CustomerProtos.Customer.EmailAddress.getDefaultInstance();
        }

        public CustomerProtos.Customer.EmailAddress build() {
          CustomerProtos.Customer.EmailAddress result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public CustomerProtos.Customer.EmailAddress buildPartial() {
          CustomerProtos.Customer.EmailAddress result = new CustomerProtos.Customer.EmailAddress(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.email_ = email_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CustomerProtos.Customer.EmailAddress) {
            return mergeFrom((CustomerProtos.Customer.EmailAddress)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CustomerProtos.Customer.EmailAddress other) {
          if (other == CustomerProtos.Customer.EmailAddress.getDefaultInstance()) return this;
          if (other.hasEmail()) {
            bitField0_ |= 0x00000001;
            email_ = other.email_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasEmail()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CustomerProtos.Customer.EmailAddress parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CustomerProtos.Customer.EmailAddress) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object email_ = "";
        /**
         * <code>required string email = 1;</code>
         */
        public boolean hasEmail() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string email = 1;</code>
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              email_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string email = 1;</code>
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string email = 1;</code>
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string email = 1;</code>
         */
        public Builder clearEmail() {
          bitField0_ = (bitField0_ & ~0x00000001);
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>required string email = 1;</code>
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          email_ = value;
          onChanged();
          return this;
        }

        private int type_ = 2;
        /**
         * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
         */
        public CustomerProtos.Customer.EmailType getType() {
          CustomerProtos.Customer.EmailType result = CustomerProtos.Customer.EmailType.valueOf(type_);
          return result == null ? CustomerProtos.Customer.EmailType.PROFESSIONAL : result;
        }
        /**
         * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
         */
        public Builder setType(CustomerProtos.Customer.EmailType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.test.Customer.EmailType type = 2 [default = PROFESSIONAL];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = 2;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.test.Customer.EmailAddress)
      }

      // @@protoc_insertion_point(class_scope:com.test.Customer.EmailAddress)
      private static final CustomerProtos.Customer.EmailAddress DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CustomerProtos.Customer.EmailAddress();
      }

      public static CustomerProtos.Customer.EmailAddress getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      public static final com.google.protobuf.Parser<EmailAddress> PARSER =
          new com.google.protobuf.AbstractParser<EmailAddress>() {
        public EmailAddress parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new EmailAddress(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<EmailAddress> getParserForType() {
        return PARSER;
      }

      public CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>required string firstName = 2;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>required string lastName = 3;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    private java.util.List<CustomerProtos.Customer.EmailAddress> email_;
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    public java.util.List<CustomerProtos.Customer.EmailAddress> getEmailList() {
      return email_;
    }
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    public java.util.List<? extends CustomerProtos.Customer.EmailAddressOrBuilder>
        getEmailOrBuilderList() {
      return email_;
    }
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    public int getEmailCount() {
      return email_.size();
    }
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    public CustomerProtos.Customer.EmailAddress getEmail(int index) {
      return email_.get(index);
    }
    /**
     * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
     */
    public CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
        int index) {
      return email_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getEmailCount(); i++) {
        if (!getEmail(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLastNameBytes());
      }
      for (int i = 0; i < email_.size(); i++) {
        output.writeMessage(5, email_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLastNameBytes());
      }
      for (int i = 0; i < email_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, email_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProtos.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProtos.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProtos.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerProtos.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CustomerProtos.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CustomerProtos.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerProtos.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.Customer)
        CustomerProtos.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProtos.internal_static_com_test_Customer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProtos.internal_static_com_test_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerProtos.Customer.class, CustomerProtos.Customer.Builder.class);
      }

      // Construct using com.example.CustomerProtos.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEmailFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (emailBuilder_ == null) {
          email_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          emailBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProtos.internal_static_com_test_Customer_descriptor;
      }

      public CustomerProtos.Customer getDefaultInstanceForType() {
        return CustomerProtos.Customer.getDefaultInstance();
      }

      public CustomerProtos.Customer build() {
        CustomerProtos.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CustomerProtos.Customer buildPartial() {
        CustomerProtos.Customer result = new CustomerProtos.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastName_ = lastName_;
        if (emailBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            email_ = java.util.Collections.unmodifiableList(email_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.email_ = email_;
        } else {
          result.email_ = emailBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProtos.Customer) {
          return mergeFrom((CustomerProtos.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerProtos.Customer other) {
        if (other == CustomerProtos.Customer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000002;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000004;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (emailBuilder_ == null) {
          if (!other.email_.isEmpty()) {
            if (email_.isEmpty()) {
              email_ = other.email_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureEmailIsMutable();
              email_.addAll(other.email_);
            }
            onChanged();
          }
        } else {
          if (!other.email_.isEmpty()) {
            if (emailBuilder_.isEmpty()) {
              emailBuilder_.dispose();
              emailBuilder_ = null;
              email_ = other.email_;
              bitField0_ = (bitField0_ & ~0x00000008);
              emailBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEmailFieldBuilder() : null;
            } else {
              emailBuilder_.addAllMessages(other.email_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasFirstName()) {
          return false;
        }
        if (!hasLastName()) {
          return false;
        }
        for (int i = 0; i < getEmailCount(); i++) {
          if (!getEmail(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomerProtos.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomerProtos.Customer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>required string firstName = 2;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>required string lastName = 3;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<CustomerProtos.Customer.EmailAddress> email_ =
        java.util.Collections.emptyList();
      private void ensureEmailIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = new java.util.ArrayList<CustomerProtos.Customer.EmailAddress>(email_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProtos.Customer.EmailAddress, CustomerProtos.Customer.EmailAddress.Builder, CustomerProtos.Customer.EmailAddressOrBuilder> emailBuilder_;

      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<CustomerProtos.Customer.EmailAddress> getEmailList() {
        if (emailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(email_);
        } else {
          return emailBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public int getEmailCount() {
        if (emailBuilder_ == null) {
          return email_.size();
        } else {
          return emailBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public CustomerProtos.Customer.EmailAddress getEmail(int index) {
        if (emailBuilder_ == null) {
          return email_.get(index);
        } else {
          return emailBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder setEmail(
          int index, CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.set(index, value);
          onChanged();
        } else {
          emailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder setEmail(
          int index, CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.set(index, builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.add(value);
          onChanged();
        } else {
          emailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          int index, CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.add(index, value);
          onChanged();
        } else {
          emailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.add(builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          int index, CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.add(index, builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder addAllEmail(
          java.lang.Iterable<? extends CustomerProtos.Customer.EmailAddress> values) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, email_);
          onChanged();
        } else {
          emailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder clearEmail() {
        if (emailBuilder_ == null) {
          email_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          emailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public Builder removeEmail(int index) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.remove(index);
          onChanged();
        } else {
          emailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public CustomerProtos.Customer.EmailAddress.Builder getEmailBuilder(
          int index) {
        return getEmailFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
          int index) {
        if (emailBuilder_ == null) {
          return email_.get(index);  } else {
          return emailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<? extends CustomerProtos.Customer.EmailAddressOrBuilder>
           getEmailOrBuilderList() {
        if (emailBuilder_ != null) {
          return emailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(email_);
        }
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public CustomerProtos.Customer.EmailAddress.Builder addEmailBuilder() {
        return getEmailFieldBuilder().addBuilder(
            CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public CustomerProtos.Customer.EmailAddress.Builder addEmailBuilder(
          int index) {
        return getEmailFieldBuilder().addBuilder(
            index, CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .com.test.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<CustomerProtos.Customer.EmailAddress.Builder>
           getEmailBuilderList() {
        return getEmailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProtos.Customer.EmailAddress, CustomerProtos.Customer.EmailAddress.Builder, CustomerProtos.Customer.EmailAddressOrBuilder>
          getEmailFieldBuilder() {
        if (emailBuilder_ == null) {
          emailBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CustomerProtos.Customer.EmailAddress, CustomerProtos.Customer.EmailAddress.Builder, CustomerProtos.Customer.EmailAddressOrBuilder>(
                  email_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          email_ = null;
        }
        return emailBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.test.Customer)
    }

    // @@protoc_insertion_point(class_scope:com.test.Customer)
    private static final CustomerProtos.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerProtos.Customer();
    }

    public static CustomerProtos.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Customer> PARSER =
        new com.google.protobuf.AbstractParser<Customer>() {
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Customer(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    public CustomerProtos.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrganizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.Organization)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    java.util.List<CustomerProtos.Customer>
        getCustomerList();
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    CustomerProtos.Customer getCustomer(int index);
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    int getCustomerCount();
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    java.util.List<? extends CustomerProtos.CustomerOrBuilder>
        getCustomerOrBuilderList();
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.test.Organization}
   */
  public  static final class Organization extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.test.Organization)
      OrganizationOrBuilder {
    // Use Organization.newBuilder() to construct.
    private Organization(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Organization() {
      name_ = "";
      customer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Organization(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                customer_ = new java.util.ArrayList<CustomerProtos.Customer>();
                mutable_bitField0_ |= 0x00000002;
              }
              customer_.add(input.readMessage(CustomerProtos.Customer.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          customer_ = java.util.Collections.unmodifiableList(customer_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProtos.internal_static_com_test_Organization_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProtos.internal_static_com_test_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerProtos.Organization.class, CustomerProtos.Organization.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_FIELD_NUMBER = 2;
    private java.util.List<CustomerProtos.Customer> customer_;
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    public java.util.List<CustomerProtos.Customer> getCustomerList() {
      return customer_;
    }
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    public java.util.List<? extends CustomerProtos.CustomerOrBuilder>
        getCustomerOrBuilderList() {
      return customer_;
    }
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    public int getCustomerCount() {
      return customer_.size();
    }
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    public CustomerProtos.Customer getCustomer(int index) {
      return customer_.get(index);
    }
    /**
     * <code>repeated .com.test.Customer customer = 2;</code>
     */
    public CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index) {
      return customer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCustomerCount(); i++) {
        if (!getCustomer(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < customer_.size(); i++) {
        output.writeMessage(2, customer_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < customer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, customer_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static CustomerProtos.Organization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProtos.Organization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProtos.Organization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProtos.Organization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProtos.Organization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerProtos.Organization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CustomerProtos.Organization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CustomerProtos.Organization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CustomerProtos.Organization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CustomerProtos.Organization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerProtos.Organization prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.Organization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.Organization)
        CustomerProtos.OrganizationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProtos.internal_static_com_test_Organization_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProtos.internal_static_com_test_Organization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerProtos.Organization.class, CustomerProtos.Organization.Builder.class);
      }

      // Construct using com.example.CustomerProtos.Organization.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCustomerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          customerBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProtos.internal_static_com_test_Organization_descriptor;
      }

      public CustomerProtos.Organization getDefaultInstanceForType() {
        return CustomerProtos.Organization.getDefaultInstance();
      }

      public CustomerProtos.Organization build() {
        CustomerProtos.Organization result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CustomerProtos.Organization buildPartial() {
        CustomerProtos.Organization result = new CustomerProtos.Organization(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            customer_ = java.util.Collections.unmodifiableList(customer_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProtos.Organization) {
          return mergeFrom((CustomerProtos.Organization)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerProtos.Organization other) {
        if (other == CustomerProtos.Organization.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (customerBuilder_ == null) {
          if (!other.customer_.isEmpty()) {
            if (customer_.isEmpty()) {
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCustomerIsMutable();
              customer_.addAll(other.customer_);
            }
            onChanged();
          }
        } else {
          if (!other.customer_.isEmpty()) {
            if (customerBuilder_.isEmpty()) {
              customerBuilder_.dispose();
              customerBuilder_ = null;
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000002);
              customerBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCustomerFieldBuilder() : null;
            } else {
              customerBuilder_.addAllMessages(other.customer_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        for (int i = 0; i < getCustomerCount(); i++) {
          if (!getCustomer(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomerProtos.Organization parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomerProtos.Organization) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<CustomerProtos.Customer> customer_ =
        java.util.Collections.emptyList();
      private void ensureCustomerIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          customer_ = new java.util.ArrayList<CustomerProtos.Customer>(customer_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProtos.Customer, CustomerProtos.Customer.Builder, CustomerProtos.CustomerOrBuilder> customerBuilder_;

      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public java.util.List<CustomerProtos.Customer> getCustomerList() {
        if (customerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customer_);
        } else {
          return customerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public int getCustomerCount() {
        if (customerBuilder_ == null) {
          return customer_.size();
        } else {
          return customerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public CustomerProtos.Customer getCustomer(int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);
        } else {
          return customerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder setCustomer(
          int index, CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.set(index, value);
          onChanged();
        } else {
          customerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder setCustomer(
          int index, CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder addCustomer(CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(value);
          onChanged();
        } else {
          customerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          int index, CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(index, value);
          onChanged();
        } else {
          customerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          int index, CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder addAllCustomer(
          java.lang.Iterable<? extends CustomerProtos.Customer> values) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customer_);
          onChanged();
        } else {
          customerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public Builder removeCustomer(int index) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.remove(index);
          onChanged();
        } else {
          customerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public CustomerProtos.Customer.Builder getCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
          int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);  } else {
          return customerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public java.util.List<? extends CustomerProtos.CustomerOrBuilder>
           getCustomerOrBuilderList() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customer_);
        }
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public CustomerProtos.Customer.Builder addCustomerBuilder() {
        return getCustomerFieldBuilder().addBuilder(
            CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public CustomerProtos.Customer.Builder addCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().addBuilder(
            index, CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.test.Customer customer = 2;</code>
       */
      public java.util.List<CustomerProtos.Customer.Builder>
           getCustomerBuilderList() {
        return getCustomerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProtos.Customer, CustomerProtos.Customer.Builder, CustomerProtos.CustomerOrBuilder>
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CustomerProtos.Customer, CustomerProtos.Customer.Builder, CustomerProtos.CustomerOrBuilder>(
                  customer_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.test.Organization)
    }

    // @@protoc_insertion_point(class_scope:com.test.Organization)
    private static final CustomerProtos.Organization DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerProtos.Organization();
    }

    public static CustomerProtos.Organization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Organization> PARSER =
        new com.google.protobuf.AbstractParser<Organization>() {
      public Organization parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Organization(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Organization> getParserForType() {
      return PARSER;
    }

    public CustomerProtos.Organization getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_Customer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_test_Customer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_Customer_EmailAddress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_test_Customer_EmailAddress_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_Organization_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_test_Organization_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010com.test\"\360\001\n\010Customer\022\n\n\002i" +
      "d\030\001 \002(\005\022\021\n\tfirstName\030\002 \002(\t\022\020\n\010lastName\030\003" +
      " \002(\t\022.\n\005email\030\005 \003(\0132\037.com.test.Customer." +
      "EmailAddress\032W\n\014EmailAddress\022\r\n\005email\030\001 " +
      "\002(\t\0228\n\004type\030\002 \001(\0162\034.com.test.Customer.Em" +
      "ailType:\014PROFESSIONAL\"*\n\tEmailType\022\013\n\007PR" +
      "IVATE\020\001\022\020\n\014PROFESSIONAL\020\002\"B\n\014Organizatio" +
      "n\022\014\n\004name\030\001 \002(\t\022$\n\010customer\030\002 \003(\0132\022.com." +
      "test.CustomerB\032\n\010com.testB\016CustomerProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_test_Customer_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", });
    internal_static_com_test_Customer_EmailAddress_descriptor =
      internal_static_com_test_Customer_descriptor.getNestedTypes().get(0);
    internal_static_com_test_Customer_EmailAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_test_Customer_EmailAddress_descriptor,
        new java.lang.String[] { "Email", "Type", });
    internal_static_com_test_Organization_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_test_Organization_descriptor,
        new java.lang.String[] { "Name", "Customer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
